[package]
name = "glium-brush"
version = "0.1.0"
authors = ["est31 <MTest31@outlook.com>"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/est31/glium-brush"
description = "Glium frontend for the glyph-brush text renderer"

[dependencies]
glium = { version = "0.22", default-features=false}
glyph_brush = "0.2"

[dev-dependencies]
glium = "0.22"
