[package]
name = "glium-brush"
version = "0.2.1"
authors = ["est31 <MTest31@outlook.com>"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/est31/glium-brush"
description = "RENAMED to glium-glyph"
exclude = ["fonts/**"]

[dependencies]
glium = { version = "0.22", default-features=false}
glyph_brush = "0.2"

[dev-dependencies]
glium = "0.22"
